# Generated by Django 5.0.7 on 2024-10-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WishList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='user',
        ),
    ]
