# Generated by Django 5.0.7 on 2024-10-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WishList', '0003_wishlistitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
