# Generated by Django 5.1.2 on 2024-10-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WishList', '0003_wishlistitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='nama_produk',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
