# Generated by Django 5.1.2 on 2024-10-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WishList', '0004_wishlistitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='nama_produk',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
