# Generated by Django 5.1.2 on 2024-10-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WishList', '0004_wishlistitem_nama_produk_wishlistitem_price'),
        ('WishList', '0005_wishlistitem_nama_produk'),
    ]

    operations = [
    ]
