# Generated by Django 5.1.1 on 2024-10-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestDeals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='image/placeholder-image', upload_to='image/'),
        ),
    ]
