# Generated by Django 5.1.1 on 2024-10-25 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestDeals', '0002_product_image'),
        ('products', '0003_auto_20241025_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='products.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
