# Generated by Django 5.1.1 on 2024-10-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BestDeals', '0003_alter_userinteraction_product_alter_sale_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInteraction',
        ),
    ]
