# Generated by Django 5.1.2 on 2024-10-25 08:54

from django.db import migrations
from django.core.management import call_command

def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "products.json")

class Migration(migrations.Migration):
    dependencies = [
        ('products', '0002_product_reviews_alter_product_id_and_more'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
